name: CMake Build CI

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose the environment to run in'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - prod

jobs:
  build:
    runs-on: ubuntu-latest

    # This makes the chosen input available as an environment variable to all steps
    env:
      ENV_TYPE: ${{ github.event.inputs.environment }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # If 'dev' environment is selected, checkout 'dev' branch; otherwise default branch
        ref: ${{ github.event.inputs.environment == 'dev' && 'dev' || '' }}

    - name: Show Selected Environment
      run: |
        echo "----------------------------------------"
        echo "Deploying/Building for environment: $ENV_TYPE"
        echo "----------------------------------------"

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Build Project
      run: cmake --build ${{github.workspace}}/build --config Release

    - name: Run Executable
      run: ${{github.workspace}}/build/my_program