name: CMake Build CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: dev

    - name: Configure CMake
      # This step triggers CMake Time. FetchContent will download the JSON library here.
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Build Project
      # This step triggers Build Time. Your code and the JSON library are compiled here.
      run: cmake --build ${{github.workspace}}/build --config Release

    - name: Run Executable
      # Verify that everything linked correctly and runs end-to-end
      run: ${{github.workspace}}/build/my_program